### ISSUE TITLE
Improve Helm Chart Values

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1148]
Improve default values

- Sort items in `Values.yaml`
- Enable autoscaling
- Update image pullPolicy
- Update test to utilize postman pod
- Set termination graceful shutdown period

**Comment by steven-sheehy** [comment]
Should consider setting a default resources in the chart to help other relay operators and to answer the question they will have "What are your resource requirements?.

Should also set cpu limit and requests equal to get strict scheduling. Since nodejs is single threaded should set cpu to 1.1. With strict scheduling you can be sure your not being throttled or competing for limited resources.

**Comment by Nana-EC** [comment]
Resolved with https://github.com/hashgraph/hedera-json-rpc-relay/pull/1149
