### ISSUE TITLE
Sudden IP rate limit errors on testnet.hashio even if requests per minute are minimal

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1284]
### Description

Might be related to this https://github.com/hashgraph/hedera-json-rpc-relay/releases/tag/v0.23.5 but testnet.hash.io rpc now returns IP rate limit errors even if they are just 1-5 read requests.

```
a78b8.js:1 Error: missing revert data in call exception (error={"reason":"bad response","code":"SERVER_ERROR","status":400,"headers":{"content-length":"202","content-type":"application/json; charset=utf-8"},"body":"{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":-32605,\"name\":\"IP Rate limit exceeded\",\"message\":\"[Request ID: 2baa8f01-3028-4914-bbf9-70736e04b877] IP Rate limit exceeded on Rate limit exceeded on eth_call\"}}","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x0000000000000000000000000000000000a210d6\",\"data\":\"0x6ce22bc1\"},\"latest\"],\"id\":53,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://testnet.hashio.io/api"}, data="0x", code=CALL_EXCEPTION, version=providers/5.5.2)
 ```

### Steps to reproduce

1. Use testnet.hashio.io/rpc
2. Call some 1-5 read functions asynchronously from contract
3. This IP rate limit error appears halting the request

### Hedera network

testnet

### Version

n/a

### Operating system

macOS

**Comment by Nana-EC** [comment]
Thanks @kabaluyot 
Thanks for highlighting this. Yes, this is related to the 0.23.5 update.

This is by design, but we should add a bit more info here as some wires are getting crossed.
This rate limit is not based on IP but rather more general due to high load on the mirror node in retrieving the information.
We pass this back to the user as a rate limit.

We'll take an item to distinguish this rate limit from the existing IP rate limit error message.

To clarify was this a one time occurrence or are you saying you and continuously experience this behavior?

**Comment by kabaluyot** [comment]
Continuously experiencing this behavior. Seems like it's getting harder to develop dapps with the limitation considering it's a public "testnet".

**Comment by Nana-EC** [comment]
@kabaluyot we had identified the issue for the mirror node rate limiting that was affecting HashIO and had resolved it in the mainnet instance.
We've now also resolved it in the previewnet and testnet instances.
Please let me know if you're still experiencing this for some reason

**Comment by Nana-EC** [comment]
No response on this and the issues is believe to have been addressed. Closing this out
