### ISSUE TITLE
[Design] Explore rpc method aware CDN caching

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1473]
### Problem

Currently the relay utilizes in app method method based caching as necessary.
While this is sufficient, to support large scaling it would be beneficial to reduce load on app pods in the helm architecture with an open source component that could cache prior to requests hitting the relay server app pods.

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
Thanks for the exploration here.
@AlfredoG87 can you close this and open an exploration ticket for https://github.com/RequestNetwork/json-rpc-proxy in the backlog

**Comment by AlfredoG87** [comment]
I already did a exploration of the `RequestNetwork/json-rpc-proxy` and was discarded since it does not allow for configurable TTL per method.

That said, I found this other candidate that might be what we are looking for, will add it to the backlog.
https://github.com/ethereum-optimism/optimism/tree/develop/proxyd

**Comment by AlfredoG87** [comment]
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1689
