### ISSUE TITLE
Implement `eth_newPendingTransactionFilter`

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1490]
### Problem

As a developer I'd like to be able to call eth_newPendingTransactionFilter and create a filter for new pending transactions.

⚠️ However due to the reason that we are fetching this information from the mirror-node and transactions there are already processed, we cannot implement this filter.

### Solution

**Parameters**
-

This method does not accept any parameters

**Returns**
- 

- NOT IMPLEMENTED

**Comment by historychronicle88** [comment]
Hey there! 👋 Thanks for sharing your concern about the `eth_newPendingTransactionFilter` method. It's unfortunate that we're unable to implement this filter due to the current setup where we fetch information from the mirror-node, and the transactions there are already processed. 

As for a solution, we regret to inform you that at the moment, we don't have an alternative in place. This means that the `eth_newPendingTransactionFilter` method is not implemented in our current configuration. We understand that this might be disappointing, and we apologize for any inconvenience caused. 

If you have any further questions or need assistance with other aspects, please feel free to let us know. We're here to help!
