### ISSUE TITLE
Cannot read property 'balance' (in getBalance)

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1608]
### Description

Spinning up own node and checking logs when interacting with wallets/contracts, it is returning an error related to 'balance' parsing.

### Steps to reproduce

1. Check and listen to json rpc logs
2. Add/import ERC20 tokens via MetaMask
3. The json rpc awfully loads slow and some errors are shown in logs

Please see attachment.

### Additional context

<img width="1265" alt="Screen Shot 2023-08-07 at 6 02 23 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/b54319d9-6db4-41c8-8b46-5e819a2e0f6b">

### Hedera network

testnet

### Version

main branch, also seen in v0.29.0

### Operating system

None

**Comment by AlfredoG87** [comment]
Hi @kabaluyot Thank you for reporting, we will be taking a look. 👍

**Comment by AlfredoG87** [comment]
I found some log examples on testnet.

https://cloudlogging.app.goo.gl/N5bfg52FSFWx4oSLA

https://cloudlogging.app.goo.gl/zNw12c6yMjYFAMVk8

https://cloudlogging.app.goo.gl/NJBTKCoTMy1jVsaE7

**Comment by AlfredoG87** [comment]
Hello @kabaluyot 
This issue is resolved on both `testnet` and `previewnet`. on version `0.30.0-rc3` in a few days it will be deployed on `mainnet` with the GA version of `0.30.0`

This is duplicated with the following already closed tickets:
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1674
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1670
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1648
