### ISSUE TITLE
Add a Design Document for Batch Requests

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1875]
### Problem

We are working on allowing batch requests on the relay, however it implies several changes and design decisions that need to be written in a design doc for future reference

### Solution

Add a design document to leave in written the design decisions that were taken for batch requests feature, how it works (parallel or sequential), the implications it has on rate limits, metrics and performance.
List of tasks that will be needed to complete the feature.

**Comment by mshakeg** [comment]
batch requests are made by a hardhat forked node, I can't really test if there are any additional incompatibilities until this feature is available, but I suspect `eth_call` requests at a specified historical `blockNumber` are also essential so that too is likely to prevent functional fork tests on Hedera.
