### ISSUE TITLE
Gas Used is always 80% of the Gas Supplied

### ISSUE THREAD

**Issue by anshuman-supraoracles** [hashgraph/hedera-json-rpc-relay#2005]
### Description

Gas Used should depend on the VM computation , Storage access, signature verification. Not on the Gas Supplied.

Like if my txn takes 150K gas in general for completion then Gas Used should always be 150K irrespective of Gas Supplied ( maybe 1M or 10M)

It will also affect the products that does On-chain gas calculation on Hedera

### Steps to reproduce

 Create a contract or shoot a txn. Most of the time you can find this scenario  

or please check the transactions from this account 
https://hashscan.io/mainnet/account/0.0.4321789?app=false&p1=1&k1=1704108177.191352760&p2=1&ph=1&pt=1
https://hashscan.io/testnet/account/0x5E1BE25D4A2De0083012f1B5A8030a7023fFA5bc?ph=1&pt=1&p2=1

### Hedera network

mainnet, testnet

### Version

v.0.38.0

### Operating system

None

**Comment by AlfredoG87** [comment]
Hi, you are right the Gas should and does depends on VM computation, but on Hedera Network, if you supply much more GAS than needed to complete the execution of the transaction it wont be refunded as Ethereum.
This is by design and can find the documentation [here](https://docs.hedera.com/hedera/core-concepts/smart-contracts/hederas-evm-equivalence-goals-and-exceptions) 


![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/87c1f6e5-0230-4ee7-a15c-514608ba7f47)

You can find details on [HIP-185](https://hips.hedera.com/hip/hip-185#charging-for-reserved-but-unused-gas) section `Gas Reservation and Unused Gas Refund`

**Comment by AlfredoG87** [comment]
The fix for this is to provide only the necessary GAS for your transaction to execute, and if want to be safe, only add a little extra, so for example, I do 10% extra to be safe and don't waste any GAS.

**Comment by anshuman-supraoracles** [comment]
@AlfredoG87 Earlier(on Nov-Dec 2023) the gas_estimate module was not able to estimate the gas for a txn. We need to manually enter a higher limit.

Is it fixed now?

**Comment by AlfredoG87** [comment]
Yes, it should be fixed now.
If is not, please let me know and let's open up another ticket with the details of the `eth_estimateGas` details so we can replicate.

should we close this ticket now?

**Comment by anshuman-supraoracles** [comment]
Yes you can . Let me check whether `eth_estimateGas` is giving correct result or not
