### ISSUE TITLE
Incompatible Geth error messages

### ISSUE THREAD

**Issue by oleg07010** [hashgraph/hedera-json-rpc-relay#2127]
### Problem

We are encountering error codes which are different from what we expect in a Geth implementation. Please provide a mapping of Hedera error codes to those of Ethereum Geth.

### Solution

Need your help to resolve the issue.

**Comment by AlfredoG87** [comment]
you could use this in the meanwhile:
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/errors/JsonRpcError.ts

**Comment by AlfredoG87** [comment]
Also, is it possible for you to provide the error docs with its descriptions for GETH to map against?

**Comment by simsonraj** [comment]
@AlfredoG87 : We rely on [these](https://github.com/smartcontractkit/chainlink/blob/develop/core/chains/evm/client/errors.go) error messages mapping to react to RPC errors & decide how the transactions should be handled. So if any of these error messages are different & not covered, we will need to add them, its mostly based on Geth error messages. It would be awesome, if you could provide a list of the differences

**Comment by Nana-EC** [comment]
Thanks @simsonraj 

Currently our custom error messages are as defined is the JsonRpcError.ts file AlfredoG87 mentioned above
Let us know if that covers all the possibilities as it provides the codes and error messages.

**Comment by Nana-EC** [comment]
I'm also curious do you ever support non GEth execution clients?
Hedera uses the Besu EVM client and a custom relay. Even if we didn't have a custom relay the GETH errors would differ from other client errors.

**Comment by simsonraj** [comment]
We do support non-Geth clients, I took a look at the error messages, we can include these in our custom support, We may need some help in the future to Map 1:1 with the error categories we have with the error messages Relay returns. But I think it can be done

**Comment by acuarica** [comment]
Hi @simsonraj, what kind of errors would you need to handle coming from Hedera relay? Because we were looking at the errors you are handling and some of them are mempool related which the relay does not throw. These errors are thrown by both Geth and Hedera

- `NonceTooLow`
- `NonceTooHigh`
- `InsufficientEth` which might be [`INSUFFICIENT_ACCOUNT_BALANCE`](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7fd42a6eaa7ec0b8cdb3dfea3e22271e88f0eba6/packages/relay/src/lib/errors/JsonRpcError.ts#L68)

Given said that, we agree, as you mention, it would be best to add a Hedera-specific regexes to detect the errors that come from the relay. We can help with further error mapping if needed.

**Comment by acuarica** [comment]
Hi @simsonraj, closing this given there is not action item on the relay. Feel free to reopen if support from the relay side is needed.
