### ISSUE TITLE
No matching record found for transaction id xx

### ISSUE THREAD

**Issue by SergioIOB** [hashgraph/hedera-json-rpc-relay#2131]
### Description

Since a few days ago we are getting an error when doing an eth_sendRawTransaction from web3j, this makes that instead of returning the TransactionReceipt object with the transaction hash it throws an exception making it impossible to retrieve the hash in evm form from the same RPC call, previously it was working correctly

`Invalid response received: 500; {"error":{"code":-32603,"name":"Internal error","message":"[Request ID: b930545c-bdb3-4e18-ae9c-3ac181105f62] Error invoking RPC: No matching record found for transaction id 0.0.1904@1708508508.906029973"},"jsonrpc":"2.0","id":8}`

### Steps to reproduce

1 - Deploy a contract with hardhat
2 - Try to call any write method with web3j, method ethSendRawTransaction

### Additional context

It is currently happening to me with any newly deployed contract, with older contracts it only happens in some cases.

I think these issues might be related

https://github.com/hashgraph/hedera-json-rpc-relay/issues/1907
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1708
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1688

### Hedera network

testnet

### Version

The latest version of the testnet

### Operating system

None

**Comment by AlfredoG87** [comment]
Hello @SergioIOB,

I guess this is in local-node environment, I have seen this happen, and happens due to `local-node` is accelerated in trying to retrieve the record from the mirror node, however sometimes it gives up before the record is processed and exposed by the mirror node. we will look at a long term fix for the relay when using the local-node.

however I might recommend you to add the following config to your relay.

`MIRROR_NODE_GET_CONTRACT_RESULTS_RETRIES=20`

I have raised a [PR](https://github.com/hashgraph/hedera-local-node/pull/551/files) for productizing this fix on the local-node, however you can clone the repo, apply the changes and start the local node using:

```
npm run start -- --network local -d
```

**Comment by SergioIOB** [comment]
Hi @AlfredoG87, thanks for the reply, but it is happening to us in the testnet, a write method is called with eth_sendRawTransaction and it returns a 500 error, saying that the transaction doesn't exist, but it does

You can see the transaction that I put in the issue in hashscan
https://hashscan.io/testnet/transaction/1708508518.753615003

Thanks anyway

**Comment by SergioIOB** [comment]
Hello! we have spoken with our RPC Relay provider (Arkhia) and changing this parameter has been solved

MIRROR_NODE_GET_CONTRACT_RESULTS_RETRIES=20

We don't know why it has started to happen, we understand that because of some change in one of the last versions, but for now everything is fixed
