### ISSUE TITLE
Issues with `eth_getlogs` API

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2175]
### Description

I have a sample transaction ([here](https://hashscan.io/testnet/contract/0.0.3665157?p=1&k=1709721331.243569998)) that has a log, but cannot be queried through the `eth_getLogs` api

And using `fromBlock` & `toBlock` seems to have no effect at all & cannot also query with the `blockHash` as per [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md)

### Steps to reproduce

```
{
	"jsonrpc":"2.0",
	"method":"eth_getLogs",
	"params":[{
		"topics":[
			"0x87f16aa184eca14ea45e132328a5effbb79b9f921657bd03d83608f26d76f3cf"
		],
        "address":"0x0ed544cdac078ba3bc354b2458c04e358e758c9a"
      
	}],
	"id":1
}
```

### Hedera network

testnet

### Version

v2.0

### Operating system

None

**Comment by simsonraj** [comment]
@Nana-EC : I see, I understand the constraint, our protocol actually requires access to the whole logs, at least since the deployment of our contracts, always. When the node starts, it gets the configuration emitted via logs and uses that to start the node, if its unable to query the logs the nodes cannot start, we can always try to pass from & toBlock. However, we still would need unrestricted access to the full logs of the node. 
It would be the same as how other chains achieve this with full node or archive node, cannot hedera be setup in such a way?

**Comment by Nana-EC** [comment]
> @Nana-EC : I see, I understand the constraint, our protocol actually requires access to the whole logs, at least since the deployment of our contracts, always. When the node starts, it gets the configuration emitted via logs and uses that to start the node, if its unable to query the logs the nodes cannot start, we can always try to pass from & toBlock. However, we still would need unrestricted access to the full logs of the node. 
> 
> It would be the same as how other chains achieve this with full node or archive node, cannot hedera be setup in such a way?

Hi @simsonraj .
Makes sense.
You should just be able to query from the block your contract was deployed then with additional batching considerations.

To confirm all the logs are accessible.
You can query from Genesis with the appropriate toBlock to manage the size of the results.

Sounds like the issue is, there are cases where you want to make a single call with no block range filter and get all the logs for your contract for all of history from its deployment without batching. Is that correct?

I belive other RPCs have limits on the log return size also but you may not have hit them yet to date.
If you have is a similar strategy for management applicable here?

If this is a blocker can you help with more details as to why this might be challenging and we can see what to explore to assist you.
The concern here is scale and the amount of logs that are possible on Hedera.
Other chains may have not experienced this yet but they will with time.

Thanks and looking forward to working through this.

**Comment by Nana-EC** [comment]
@simsonraj which other RPCs are you using.
Both Alchemy and Infura exhibit similar constriants.

See https://docs.alchemy.com/reference/eth-getlogs#use-cases-for-eth_getlogs and https://docs.infura.io/api/networks/ethereum/json-rpc-methods/eth_getlogs#constraints where either the log amount is limited or timeouts are expected and range is recommended

**Comment by Nana-EC** [comment]
@simsonraj one thing that @acuarica just pointed out is, we fail in advance when the block range is too large. Whereas the other RPCs would just return the first 1000 blocks worth of logs or timeout.

Maybe this is what you're seeing as an unexpected behavior.

We could look into modifying this but it could be argued that's a regression in developer UX.
Many would prefer to be told if the limit instead of having to figure out the response was called.

Curious on your experience here.
