### ISSUE TITLE
Acceptence test reports improvements

### ISSUE THREAD

**Issue by isavov** [hashgraph/hedera-json-rpc-relay#2571]
### Problem

- Currently when re-running failed pipelines for the `Acceptance tests` workflow the `Publish results` step can access only the reports from the current run. Therefore the reports can't be published in their entirety or in rare cases at all.

### Solution

- Update the workflow to access test reports from previous runs with the same commit hash

### Alternatives

-

**Comment by yaroslav-007** [comment]
Hello,

With Ilia we have checked this issue was opened by mistake in the relay and was related to `hedera-smart-contracts` repo where change in versions of `actions/download-artifact` and `actions/upload-artifact` caused issue (
`Artifacts v4 is not cross-compatible with previous versions. For example, an artifact uploaded using v3 cannot be used with actions/download-artifact@v4.` https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) and this was reverted in https://github.com/hashgraph/hedera-smart-contracts/commit/810cc980786b86821610935bc04823d92c180e8c

I would consider it fixed at this point and closing this one.
