### ISSUE TITLE
Helm chart generates invalid json for HEDERA_NETWORK

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-json-rpc-relay#2585]
### Description

There is an issue in `charts/hedera-json-rpc-relay/templates/configmap.yaml`. The generated value for `HEDERA_NETWORK` is an invalid JSON string and cannot be parsed. Example:
```
{map[network-node0-0:50211:0.0.3 network-node1-0:50211:0.0.3 network-node2-0:50211:0.0.3}
```

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by AlfredoG87** [comment]
@Ivo-Yankov  could you share the helm command you are using to execute the chart and generate the template?

**Comment by Ivo-Yankov** [comment]
Hello Fredy, this is the command I am using. It is the one generated by [solo](https://github.com/hashgraph/solo/) when starting the relay:

```
helm install relay-node0-node1-node2 hedera-json-rpc-relay/hedera-json-rpc-relay  -n solo --create-namespace  --values /home/ivo/.solo/cache/values-files/rpcRelay-local.yaml --set config.MIRROR_NODE_URL=http://10.244.0.19:5551 --set config.MIRROR_NODE_URL_WEB3=http://10.244.0.17:8545 --set config.CHAIN_ID=298 --set image.tag=0.48.0 --set replicaCount=1 --set config.OPERATOR_ID_MAIN=0.0.2 --set config.OPERATOR_KEY_MAIN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --set config.HEDERA_NETWORK.network-node0-0:50211=0.0.3 --set config.HEDERA_NETWORK.network-node1-0:50211=0.0.3 --set config.HEDERA_NETWORK.network-node2-0:50211=0.0.3
```

**Comment by AlfredoG87** [comment]
I think is simpler to make the solo script to produce this output, since the helm chart is expecting a json value like this:
```
--set config.HEDERA_NETWORK='{"network-node0-0:50211":"0.0.3","network-node1-0:50211":"0.0.3","network-node2-0:50211":"0.0.3"}' 
```

Otherwise it would need a refactor on the charts and the code, to accept a collection or map and that should be processed directly by the code, without any helm transformations. otherwise is too complicated for the helm chart to figure out what is the input and do a transformation based on many distinct probabilities of inputs like simple string, a stringify json and also a map.
