### ISSUE TITLE
Capture env variables in reusable constants

### ISSUE THREAD

**Issue by victor-yanev** [hashgraph/hedera-json-rpc-relay#2686]
### Problem

Currently, we are dynamically getting the environment variables and parsing/casting them every time. This is inefficient and also, more importantly, allows env configurations to be dynamically changed, which can modify the behaviour of the relay based on the current values of the env vars, which can be a potential exploit.

### Solution

- We should change this to only capture them once when the relay is initialised and reuse those as constants

**Comment by natanasow** [comment]
@Nana-EC adding 5 as points because even a little architecture change, the entire project relies on it. The changed files are more than 110 so there is a lot of work to be done and verified. There are runtime changes of the env variables (in the test cases) and the new approach should handle them as well.

**Comment by quiet-node** [comment]
resolved in https://github.com/hashgraph/hedera-json-rpc-relay/pull/3047
