### ISSUE TITLE
go-ethereum: incorrect number of transactions returned 

### ISSUE THREAD

**Issue by jbaldwinroberts** [hashgraph/hedera-json-rpc-relay#2812]
### Description

go-ethereum is returning the incorrect number of transactions

### Steps to reproduce
```
func TestHederaParseBlock(t *testing.T) {
	ctx := context.Background()

	ethClient, err := eth.Dial("https://testnet.hashio.io/api")
	require.NoError(t, err)

	block, err := ethClient.BlockByNumber(ctx, big.NewInt(7771665))
	require.NoError(t, err)

	log.Infof("number of block transactions, %v", len(block.Transactions())) // 1

	rpcClient, err := rpc.Dial("https://testnet.hashio.io/api")
	require.NoError(t, err)

	var result map[string]interface{}
	err = rpcClient.Call(
		&result, "eth_getBlockByNumber", toBlockNumArg(big.NewInt(7771665)), true,
	)
	require.NoError(t, err)
	
	log.Infof("number of rpc transactions, %v", len(result["transactions"].([]interface{}))) // 1
}
```

The above prints `1`, whereas `https://hashscan.io/testnet/block/7771665` shows `9`.

### Hedera network

testnet

### Version

NA

### Operating system

macOS

**Comment by arianejasuwienas** [comment]
@jbaldwinroberts thank you for bringing this to our attention and for your support.

The difference you're seeing occurs because Hedera Consensus Service Submit Messages are not included in the results when querying block data via the Hedera JSON-RPC API.

To retrieve the complete list of transactions stored on a specific block, you can use the following script:
```bash
curl -X POST https://testnet.hashio.io/api \
-H "Content-Type: application/json" \
-d '{
    "jsonrpc":"2.0",
    "method":"eth_getBlockByNumber",
    "params": [
        "0x769611",  // Block number in hexadecimal (7771665 in decimal is 0x769611 in hex)
        true
    ],
    "id":1
}'
```
Please note that this behaviour is tied to the architecture of the Hedera services, rather than the Golang client itself.
If you have any further questions or need additional assistance, please don't hesitate to reach out.

**Comment by ebadiere** [comment]
@jbaldwinroberts To add to @arianejasuwienas point, the above JSON RPC call will return ethereum related as well as crypto transfer transactions, and there is one crypto transfer transaction in that block.
