### ISSUE TITLE
Revert reason not sent back in reverted contract call

### ISSUE THREAD

**Issue by BjMrq** [hashgraph/hedera-json-rpc-relay#492]
## Description

When sending a call to a contract that would revert the relayer respond with a `"Unknown error invoking RPC"` instead of responding that the query result ended up in a revert with the revert reason. The json-relayer is actually aware that the error from the query is due to a contract call reverted it seem, in the log I see the following error
transaction 0.0.47814462@1661172942.961021307 failed precheck with status CONTRACT_REVERT_EXECUTED status: 33
but this information is not returned.

Example call
```
curl https://node_endpoint/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"to":"0x1b68bA912B7AC0Cf771F36ac356Bbceda299fbcf","data":"0x20965255"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```
response: 
```
{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d53657420746f2072657665727400000000000000000000000000000000000000","message":"execution reverted: Set to revert"}}
```
0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d53657420746f2072657665727400000000000000000000000000000000000000
which indicate that the call was reverted and includes the revert reason

### Steps to reproduce

- Send a call on a contract that would revert to the json relayer 

### Hedera network

testnet

### Version

testnet

**Comment by Nana-EC** [comment]
@BjMrq thanks for the ticket.

Notably, revert reasons can happen for different reasons and at different points in the flow.
In terms of the flow, the revert reason is not returned as part of the consensus node call.
So though you see the log in the relay, it's only telling you the type of error but not the revert reason.

For `eth_call` since it's a local node query the details actually don't make it off that node.

Could you provide more context including 
- which tool you're using and the call 
- sample contract for your case.

I'm also not sure where you got that response from (with code, data and message) either so that context would also be helpful.

**Comment by Nana-EC** [comment]
Depends on https://github.com/hashgraph/hedera-sdk-js/issues/1261

**Comment by Nana-EC** [comment]
sdk-js has released https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.18.3 which should expose ContractFunctionResult.
Let's verify it provides the needed info
