### ISSUE TITLE
Add rate limit by HBAR support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#528]
### Problem

After the solution to #426 rate limiting by number of requests per IP will be supported.
However, it would be good to support consumption based rate limiting.

### Solution

Add logic that tracks the relay consumption rate and rate limits on this metric also

**Comment by mshakeg** [comment]
Hi @Nana-EC would it be possible for Swirlds to update the `HBAR_RATE_LIMIT_TINYBAR` on the testnet and mainnet hashio relays beyond the 50 HBAR default?

Assume a price of $0.6/HBAR then 50 HBAR is $3 which at the current gas price of $0.000_000_0569/gas allows for 52_724_077 gas/60s(i.e. 60s is the default `HBAR_RATE_LIMIT_DURATION`) which means the hashio relay allows for an average of ~880k gas/s to be spent for `eth_calls` which is really low for all dApps utilising the hashio relay to share.

I'd recommend setting `HBAR_RATE_LIMIT_TINYBAR` to 300 HBAR as this would allow for 6x the current gas/s throughput i.e. ~316m gas/HBAR_RATE_LIMIT_DURATION or ~5.2m gas/s.

This is a temporary measure to avoid negatively impacting dApps that heavily utilise eth_calls until HIP-584 is production ready and the `HBAR_RATE_LIMIT_TINYBAR` could then potentially be decreased back to 50 HBAR.

**Comment by mshakeg** [comment]
Hi @Nana-EC another thought that comes to mind if increasing the `HBAR_RATE_LIMIT_TINYBAR` by 6x would not be feasible(due to for example the HBAR spent by the hashio relay not being entirely refundable for whatever reason) would be to charge a separate and cheaper gas price for `ContractCallQuery` requests than for `ContractExecuteTransaction`.

IMO the gas price should be about `~NUMBER_OF_NODES^2` cheaper, as:
1. it is computationally cheaper since a `ContractCallQuery` request is only executed by a single node and
2. has a greater supply to handle this request as it can be executed by any of the total number of nodes
whereas a `ContractExecuteTransaction` is executed by every single node in the network.

So based on the current `NUMBER_OF_NODES` on mainnet(i.e 28) a reasonable gas price for `ContractCallQuery` requests could be 784(28^2) cheaper than that of `ContractExecuteTransaction` or at the maximum number of council nodes(i.e 39) the gas price would be 1521(39^2) cheaper and so perhaps a reasonable middle ground would be 1000x cheaper i.e. $0.000_000_000_0569/gas.

**Comment by Nana-EC** [comment]
Hi @mshakeg 
Gas pricing isn't something we could change fork the relay.
The gas prices ensure network security so it would require at least a HIP and further discussion into implications.

From the eth_call side HIP 584 is making progress and 0.36/0.37 will eventually see calls via the relay utilizing the mirror node for state. Thresholds will then be less likely to get hit.

**Comment by mshakeg** [comment]
Hi @Nana-EC

> The gas prices ensure network security so it would require at least a HIP and further discussion into implications.

I suspected as much hence why I created this [HIP idea discussion](https://github.com/hashgraph/hedera-improvement-proposal/discussions/712)
