### ISSUE TITLE
Transaction Receipt fails to handle undefined transaction index

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#692]
### Description

Transaction receipt calls occasionally fail with the following with the transaction_index value is missing
```
TypeError: Cannot read properties of undefined (reading 'toString') at Function.numberTo0x 
```

### Steps to reproduce

1. Call eth_getTransactionReceipt for a transaction where Mirror Node does not populate the `transaction_index` filed

e.g. https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x0339477ac4e9516be0bca4e1634b250c8fe431b4fce1ced136eccb516ed456fa

### Hedera network

testnet

### Version

v0.11.0

**Comment by dimitrovmaksim** [comment]
My wild guess is that, because for the purpose of returning both eth and hedera transactions by hash, we now use fetch the transaction info from the contract_result table and use the ContractResults model which in the constructor just maps whatever keys it receives https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/model/contractResult.js#L27. Looking at the transaction, it is a failed one, with the `INVALID_ACCOUNT_ID` error, and because it's a failed transaction it does not have an index, because it was not added to a block. And if `JSON.stringify` is used to return the response from the mirror node, it will remove all fields with `undefined` values.

**Comment by Nana-EC** [comment]
@dimitrovmaksim sounds right. I fixed the null handling issue here on the relay but the data is still wrong
Opened https://github.com/hashgraph/hedera-mirror-node/issues/4893

**Comment by Nana-EC** [comment]
Closing as undefined issue was fixed. Null issue must be fixed my mirror node
