### ISSUE TITLE
Add k6 performance tests to release process

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#867]
### Problem

We have an initial form of [k6 perf testing](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/k6).
However, we need to expand it's usage and utilize it during release steps

### Solution

1. Confirm state of k6 tests and make tickets for any improvements need to be made
2. Run tests to get soft assessments of load support across the applications and the performance of different methods
3. Run tests in 0.18 release steps

**Comment by AlfredoG87** [comment]
The PR #899  covers fixes needed to individual tests, and improvements to the process of running the tests by providing a preparation script and nodejs package to wrap the test process. This improvements were made as part of current ticket since they were a pre-requisite to be able to complete points (2) and (3).


For further improvements the follow issues were created:
https://github.com/hashgraph/hedera-json-rpc-relay/issues/948
https://github.com/hashgraph/hedera-json-rpc-relay/issues/949
